/*
 * sick.h
 *
 *  Created on: 27 de jan de 2016
 *      Author: cuki
 */

#ifndef SICK_H_
#define SICK_H_

#define EXIT_SUCESS		0
#define EXIT_ERROR		0xFF
#define DSF60_ADDRESS	0x40
#define BUFFER_MAX		0x80
#define ENCODER_EN		PIN_C2

typedef enum dsf60_command_e {
	DSF60_COMMAND_ENCODER_RESET = 0x53,
	DSF60_COMMAND_READ_SERIAL_NUMBER = 0x56,
	DSF60_COMMAND_READ_POSITION = 0x92,
	DSF60_COMMAND_SET_NUMBER_OF_LINES = 0x96,
	DSF60_COMMAND_SET_ELECTRICAL_INTERFACE,
	DSF60_COMMAND_SET_ZERO_PULSE_WIDTH_ELECTRICAL,
	DSF60_COMMAND_ZERO_SET,
	DSF60_COMMAND_READ_ENCODER_TYPE,
	DSF60_COMMAND_SET_ZERO_PULSE_WIDTH_MECHANICAL,
	DSF60_COMMAND_READ_ZERO_PULSE_WIDTH_ELECTRIAL_MECHANICAL,
	DSF60_COMMAND_READ_ELECTRICAL_INTERFACE
} DSF60_command_t;

#endif /* SICK_H_ */
